cask_args appdir: '/Applications', require_sha: 'true'

# Taps
tap 'd12frosted/emacs-plus' || true
tap 'neovim/neovim' || true
tap 'homebrew/cask-fonts' || true

# Tools
brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'bat-extras'
brew 'cmake'  # For Emacs' vterm
brew 'coreutils'
brew 'docker'
brew 'emacs-plus@29', args: ["--with-xwidgets", "--with-imagemagick", "--with-native-comp", "--with-no-frame-refocus"]
brew 'exa'
brew 'fasd'
brew 'fd'
brew 'fzf'
brew 'gawk'
brew 'gcc'
brew 'git'
brew 'git-open'
brew 'git-delta'
brew 'go'
brew 'graphviz'  # Provides dot etc.
brew 'htop'
brew 'imagemagick'
brew 'libgccjit'  # For Emacs native compilation
brew 'libtool'  # For Emacs' vterm
brew 'ncdu'
brew 'neovim'
brew 'node'
brew 'ranger'
brew 'ripgrep'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'wget'

# [2023-05-27 Sat] Actually need to manually pin this at 2.4.0
# for now - see https://www.reddit.com/r/emacs/comments/137r7j7/gnupg_241_encryption_issues_with_emacs_orgmode/
#brew 'gnupg'

# Fonts
cask 'font-inconsolata'
cask 'font-input'
cask 'font-iosevka'

# MacOS applications
cask 'spotify', args: {require_sha: false}
cask 'mactex', args: {require_sha: false}
