# ANSI escape codes
export ANSIreset="\[$(tput sgr0)\]"
export ANSInone="\[\e[00m\]"
export ANSIblack="\[\e[00;30m\]"
export ANSIbrightblack="\[\e[01;30m\]"
export ANSIred="\[\e[00;31m\]"
export ANSIbrightred="\[\e[01;31m\]"
export ANSIgreen="\[\e[00;32m\]"
export ANSIbrightgreen="\[\e[01;32m\]"
export ANSIyellow="\[\e[00;33m\]"
export ANSIbrightyellow="\[\e[01;33m\]"
export ANSIblue="\[\e[00;34m\]"
export ANSIbrightblue="\[\e[01;34m\]"
export ANSImagenta="\[\e[00;35m\]"
export ANSIbrightmagenta="\[\e[01;35m\]"
export ANSIcyan="\[\e[00;36m\]"
export ANSIbrightcyan="\[\e[01;36m\]"
export ANSIwhite="\[\e[00;37m\]"
export ANSIbrightwhite="\[\e[01;37m\]"

eval $(dircolors -b $DOTFILES/dircolors.ansi-universal)
